// <auto-generated />
namespace EmbracingMemories.QrProfileMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangerequiredfieldsonLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangerequiredfieldsonLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201802051452140_Change required fields on Links"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
